// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "DbObject-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy


#include <odb/pgsql/traits.hxx>
#include <odb/pgsql/database.hxx>
#include <odb/pgsql/transaction.hxx>
#include <odb/pgsql/connection.hxx>
#include <odb/pgsql/statement.hxx>
#include <odb/pgsql/statement-cache.hxx>
#include <odb/pgsql/simple-object-statements.hxx>
#include <odb/pgsql/container-statements.hxx>
#include <odb/pgsql/exceptions.hxx>
#include <odb/pgsql/simple-object-result.hxx>

namespace odb
{
  // DbObject
  //

  const char alias_traits<  ::kpk::data::User,
    id_pgsql,
    access::object_traits_impl< ::kpk::data::DbObject, id_pgsql >::createdBy_tag>::
  table_name[] = "\"idUser\"";

  bool access::object_traits_impl< ::kpk::data::DbObject, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // IsDeleted base
    //
    if (object_traits_impl< ::kpk::data::IsDeleted, id_pgsql >::grow (
          i, t + 0UL))
      grew = true;

    // _createTime
    //
    t[3UL] = 0;

    // _createdBy
    //
    t[4UL] = 0;

    return grew;
  }

  void access::object_traits_impl< ::kpk::data::DbObject, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    std::size_t n (0);

    // IsDeleted base
    //
    object_traits_impl< ::kpk::data::IsDeleted, id_pgsql >::bind (b + n, i, sk);
    n += 3UL;

    // _createTime
    //
    b[n].type = pgsql::bind::timestamp;
    b[n].buffer = &i._createTime_value;
    b[n].is_null = &i._createTime_null;
    n++;

    // _createdBy
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i._createdBy_value;
    b[n].is_null = &i._createdBy_null;
    n++;
  }

  bool access::object_traits_impl< ::kpk::data::DbObject, id_pgsql >::
  init (image_type& i,
        const object_type& o,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    bool grew (false);

    // IsDeleted base
    //
    if (object_traits_impl< ::kpk::data::IsDeleted, id_pgsql >::init (i, o, sk))
      grew = true;

    // _createTime
    //
    {
      ::QDateTime const& v =
        o._createTime;

      bool is_null (true);
      pgsql::value_traits<
          ::QDateTime,
          pgsql::id_timestamp >::set_image (
        i._createTime_value, is_null, v);
      i._createTime_null = is_null;
    }

    // _createdBy
    //
    {
      ::std::shared_ptr< ::kpk::data::User > const& v =
        o._createdBy;

      typedef object_traits< ::kpk::data::User > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::kpk::data::User > > ptr_traits;

      bool is_null (ptr_traits::null_ptr (v));
      if (!is_null)
      {
        const obj_traits::id_type& id (
          obj_traits::id (ptr_traits::get_ref (v)));

        pgsql::value_traits<
            obj_traits::id_type,
            pgsql::id_bigint >::set_image (
          i._createdBy_value, is_null, id);
        i._createdBy_null = is_null;
      }
      else
        throw null_pointer ();
    }

    return grew;
  }

  void access::object_traits_impl< ::kpk::data::DbObject, id_pgsql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // IsDeleted base
    //
    object_traits_impl< ::kpk::data::IsDeleted, id_pgsql >::init (o, i, db);

    // _createTime
    //
    {
      ::QDateTime& v =
        o._createTime;

      pgsql::value_traits<
          ::QDateTime,
          pgsql::id_timestamp >::set_value (
        v,
        i._createTime_value,
        i._createTime_null);
    }

    // _createdBy
    //
    {
      ::std::shared_ptr< ::kpk::data::User >& v =
        o._createdBy;

      typedef object_traits< ::kpk::data::User > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::kpk::data::User > > ptr_traits;

      if (i._createdBy_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type id;
        pgsql::value_traits<
            obj_traits::id_type,
            pgsql::id_bigint >::set_value (
          id,
          i._createdBy_value,
          i._createdBy_null);

        // If a compiler error points to the line below, then
        // it most likely means that a pointer used in a member
        // cannot be initialized from an object pointer.
        //
        v = ptr_traits::pointer_type (
          static_cast<pgsql::database*> (db)->load<
            obj_traits::object_type > (id));
      }
    }
  }
}

#include <odb/post.hxx>
