// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "IsDeleted-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy


#include <odb/pgsql/traits.hxx>
#include <odb/pgsql/database.hxx>
#include <odb/pgsql/transaction.hxx>
#include <odb/pgsql/connection.hxx>
#include <odb/pgsql/statement.hxx>
#include <odb/pgsql/statement-cache.hxx>
#include <odb/pgsql/simple-object-statements.hxx>
#include <odb/pgsql/container-statements.hxx>
#include <odb/pgsql/exceptions.hxx>
#include <odb/pgsql/simple-object-result.hxx>

namespace odb
{
  // IsDeleted
  //

  bool access::object_traits_impl< ::kpk::data::IsDeleted, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // _isDeleted
    //
    t[0UL] = 0;

    // _deleteDate
    //
    t[1UL] = 0;

    return grew;
  }

  void access::object_traits_impl< ::kpk::data::IsDeleted, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    std::size_t n (0);

    // _isDeleted
    //
    b[n].type = pgsql::bind::boolean_;
    b[n].buffer = &i._isDeleted_value;
    b[n].is_null = &i._isDeleted_null;
    n++;

    // _deleteDate
    //
    b[n].type = pgsql::bind::date;
    b[n].buffer = &i._deleteDate_value;
    b[n].is_null = &i._deleteDate_null;
    n++;
  }

  bool access::object_traits_impl< ::kpk::data::IsDeleted, id_pgsql >::
  init (image_type& i,
        const object_type& o,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    bool grew (false);

    // _isDeleted
    //
    {
      bool const& v =
        o._isDeleted;

      bool is_null (false);
      pgsql::value_traits<
          bool,
          pgsql::id_boolean >::set_image (
        i._isDeleted_value, is_null, v);
      i._isDeleted_null = is_null;
    }

    // _deleteDate
    //
    {
      ::std::shared_ptr< ::QDate > const& v =
        o._deleteDate;

      bool is_null (true);
      pgsql::value_traits<
          ::std::shared_ptr< ::QDate >,
          pgsql::id_date >::set_image (
        i._deleteDate_value, is_null, v);
      i._deleteDate_null = is_null;
    }

    return grew;
  }

  void access::object_traits_impl< ::kpk::data::IsDeleted, id_pgsql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // _isDeleted
    //
    {
      bool& v =
        o._isDeleted;

      pgsql::value_traits<
          bool,
          pgsql::id_boolean >::set_value (
        v,
        i._isDeleted_value,
        i._isDeleted_null);
    }

    // _deleteDate
    //
    {
      ::std::shared_ptr< ::QDate >& v =
        o._deleteDate;

      pgsql::value_traits<
          ::std::shared_ptr< ::QDate >,
          pgsql::id_date >::set_value (
        v,
        i._deleteDate_value,
        i._deleteDate_null);
    }
  }
}

#include <odb/post.hxx>
