// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "Person-odb.hxx"
#include "Member-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy


#include <odb/pgsql/traits.hxx>
#include <odb/pgsql/database.hxx>
#include <odb/pgsql/transaction.hxx>
#include <odb/pgsql/connection.hxx>
#include <odb/pgsql/statement.hxx>
#include <odb/pgsql/statement-cache.hxx>
#include <odb/pgsql/simple-object-statements.hxx>
#include <odb/pgsql/container-statements.hxx>
#include <odb/pgsql/exceptions.hxx>
#include <odb/pgsql/simple-object-result.hxx>

namespace odb
{
  // Person
  //

  const char access::object_traits_impl< ::kpk::data::Person, id_pgsql >::
  persist_statement_name[] = "persist_kpk_data_Person";

  const char access::object_traits_impl< ::kpk::data::Person, id_pgsql >::
  find_statement_name[] = "find_kpk_data_Person";

  const char access::object_traits_impl< ::kpk::data::Person, id_pgsql >::
  update_statement_name[] = "update_kpk_data_Person";

  const char access::object_traits_impl< ::kpk::data::Person, id_pgsql >::
  erase_statement_name[] = "erase_kpk_data_Person";

  const char access::object_traits_impl< ::kpk::data::Person, id_pgsql >::
  query_statement_name[] = "query_kpk_data_Person";

  const char access::object_traits_impl< ::kpk::data::Person, id_pgsql >::
  erase_query_statement_name[] = "erase_query_kpk_data_Person";

  const unsigned int access::object_traits_impl< ::kpk::data::Person, id_pgsql >::
  persist_statement_types[] =
  {
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::date_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::int8_oid
  };

  const unsigned int access::object_traits_impl< ::kpk::data::Person, id_pgsql >::
  find_statement_types[] =
  {
    pgsql::int8_oid
  };

  const unsigned int access::object_traits_impl< ::kpk::data::Person, id_pgsql >::
  update_statement_types[] =
  {
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::date_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::int8_oid,
    pgsql::int8_oid
  };

  const char alias_traits<  ::kpk::data::Member,
    id_pgsql,
    access::object_traits_impl< ::kpk::data::Person, id_pgsql >::member_tag>::
  table_name[] = "\"idMember\"";

  struct access::object_traits_impl< ::kpk::data::Person, id_pgsql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      pgsql::connection&,
      image_type&,
      id_image_type&,
      pgsql::binding&,
      pgsql::binding&,
      pgsql::native_binding&,
      const unsigned int*)
    {
    }
  };

  access::object_traits_impl< ::kpk::data::Person, id_pgsql >::id_type
  access::object_traits_impl< ::kpk::data::Person, id_pgsql >::
  id (const id_image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      pgsql::value_traits<
          ::ulong,
          pgsql::id_bigint >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::kpk::data::Person, id_pgsql >::id_type
  access::object_traits_impl< ::kpk::data::Person, id_pgsql >::
  id (const image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      pgsql::value_traits<
          ::ulong,
          pgsql::id_bigint >::set_value (
        id,
        i._id_value,
        i._id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::kpk::data::Person, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // _id
    //
    t[0UL] = 0;

    // _name
    //
    if (composite_value_traits< ::kpk::data::Name, id_pgsql >::grow (
          i._name_value, t + 1UL))
      grew = true;

    // _passport
    //
    if (composite_value_traits< ::kpk::data::Passport, id_pgsql >::grow (
          i._passport_value, t + 5UL))
      grew = true;

    // _inn
    //
    if (t[10UL])
    {
      i._inn_value.capacity (i._inn_size);
      grew = true;
    }

    // _snils
    //
    if (t[11UL])
    {
      i._snils_value.capacity (i._snils_size);
      grew = true;
    }

    // _member
    //
    t[12UL] = 0;

    return grew;
  }

  void access::object_traits_impl< ::kpk::data::Person, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    std::size_t n (0);

    // _id
    //
    if (sk != statement_insert && sk != statement_update)
    {
      b[n].type = pgsql::bind::bigint;
      b[n].buffer = &i._id_value;
      b[n].is_null = &i._id_null;
      n++;
    }

    // _name
    //
    composite_value_traits< ::kpk::data::Name, id_pgsql >::bind (
      b + n, i._name_value, sk);
    n += 4UL;

    // _passport
    //
    composite_value_traits< ::kpk::data::Passport, id_pgsql >::bind (
      b + n, i._passport_value, sk);
    n += 5UL;

    // _inn
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i._inn_value.data ();
    b[n].capacity = i._inn_value.capacity ();
    b[n].size = &i._inn_size;
    b[n].is_null = &i._inn_null;
    n++;

    // _snils
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i._snils_value.data ();
    b[n].capacity = i._snils_value.capacity ();
    b[n].size = &i._snils_size;
    b[n].is_null = &i._snils_null;
    n++;

    // _member
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i._member_value;
    b[n].is_null = &i._member_null;
    n++;
  }

  void access::object_traits_impl< ::kpk::data::Person, id_pgsql >::
  bind (pgsql::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::kpk::data::Person, id_pgsql >::
  init (image_type& i,
        const object_type& o,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    bool grew (false);

    // _name
    //
    {
      ::kpk::data::Name const& v =
        o._name;

      if (composite_value_traits< ::kpk::data::Name, id_pgsql >::init (
            i._name_value,
            v,
            sk))
        grew = true;
    }

    // _passport
    //
    {
      ::kpk::data::Passport const& v =
        o._passport;

      if (composite_value_traits< ::kpk::data::Passport, id_pgsql >::init (
            i._passport_value,
            v,
            sk))
        grew = true;
    }

    // _inn
    //
    {
      ::QString const& v =
        o._inn;

      bool is_null (true);
      std::size_t size (0);
      std::size_t cap (i._inn_value.capacity ());
      pgsql::value_traits<
          ::QString,
          pgsql::id_string >::set_image (
        i._inn_value,
        size,
        is_null,
        v);
      i._inn_null = is_null;
      i._inn_size = size;
      grew = grew || (cap != i._inn_value.capacity ());
    }

    // _snils
    //
    {
      ::QString const& v =
        o._snils;

      bool is_null (true);
      std::size_t size (0);
      std::size_t cap (i._snils_value.capacity ());
      pgsql::value_traits<
          ::QString,
          pgsql::id_string >::set_image (
        i._snils_value,
        size,
        is_null,
        v);
      i._snils_null = is_null;
      i._snils_size = size;
      grew = grew || (cap != i._snils_value.capacity ());
    }

    // _member
    //
    {
      ::QSharedPointer< ::kpk::data::Member > const& v =
        o._member;

      typedef object_traits< ::kpk::data::Member > obj_traits;
      typedef odb::pointer_traits< ::QSharedPointer< ::kpk::data::Member > > ptr_traits;

      bool is_null (ptr_traits::null_ptr (v));
      if (!is_null)
      {
        const obj_traits::id_type& id (
          obj_traits::id (ptr_traits::get_ref (v)));

        pgsql::value_traits<
            obj_traits::id_type,
            pgsql::id_bigint >::set_image (
          i._member_value, is_null, id);
        i._member_null = is_null;
      }
      else
        i._member_null = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::kpk::data::Person, id_pgsql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // _id
    //
    {
      ::ulong& v =
        o._id;

      pgsql::value_traits<
          ::ulong,
          pgsql::id_bigint >::set_value (
        v,
        i._id_value,
        i._id_null);
    }

    // _name
    //
    {
      ::kpk::data::Name& v =
        o._name;

      composite_value_traits< ::kpk::data::Name, id_pgsql >::init (
        v,
        i._name_value,
        db);
    }

    // _passport
    //
    {
      ::kpk::data::Passport& v =
        o._passport;

      composite_value_traits< ::kpk::data::Passport, id_pgsql >::init (
        v,
        i._passport_value,
        db);
    }

    // _inn
    //
    {
      ::QString& v =
        o._inn;

      pgsql::value_traits<
          ::QString,
          pgsql::id_string >::set_value (
        v,
        i._inn_value,
        i._inn_size,
        i._inn_null);
    }

    // _snils
    //
    {
      ::QString& v =
        o._snils;

      pgsql::value_traits<
          ::QString,
          pgsql::id_string >::set_value (
        v,
        i._snils_value,
        i._snils_size,
        i._snils_null);
    }

    // _member
    //
    {
      ::QSharedPointer< ::kpk::data::Member >& v =
        o._member;

      typedef object_traits< ::kpk::data::Member > obj_traits;
      typedef odb::pointer_traits< ::QSharedPointer< ::kpk::data::Member > > ptr_traits;

      if (i._member_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type id;
        pgsql::value_traits<
            obj_traits::id_type,
            pgsql::id_bigint >::set_value (
          id,
          i._member_value,
          i._member_null);

        // If a compiler error points to the line below, then
        // it most likely means that a pointer used in a member
        // cannot be initialized from an object pointer.
        //
        v = ptr_traits::pointer_type (
          static_cast<pgsql::database*> (db)->load<
            obj_traits::object_type > (id));
      }
    }
  }

  void access::object_traits_impl< ::kpk::data::Person, id_pgsql >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      pgsql::value_traits<
          ::ulong,
          pgsql::id_bigint >::set_image (
        i.id_value, is_null, id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::kpk::data::Person, id_pgsql >::persist_statement[] =
  "INSERT INTO \"Person\" "
  "(\"id\", "
  "\"name_first\", "
  "\"name_middle\", "
  "\"name_last\", "
  "\"name_full\", "
  "\"pass_series\", "
  "\"pass_number\", "
  "\"pass_date\", "
  "\"pass_org\", "
  "\"pass_orgCode\", "
  "\"inn\", "
  "\"snils\", "
  "\"idMember\") "
  "VALUES "
  "(DEFAULT, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) "
  "RETURNING \"id\"";

  const char access::object_traits_impl< ::kpk::data::Person, id_pgsql >::find_statement[] =
  "SELECT "
  "\"Person\".\"id\", "
  "\"Person\".\"name_first\", "
  "\"Person\".\"name_middle\", "
  "\"Person\".\"name_last\", "
  "\"Person\".\"name_full\", "
  "\"Person\".\"pass_series\", "
  "\"Person\".\"pass_number\", "
  "\"Person\".\"pass_date\", "
  "\"Person\".\"pass_org\", "
  "\"Person\".\"pass_orgCode\", "
  "\"Person\".\"inn\", "
  "\"Person\".\"snils\", "
  "\"Person\".\"idMember\" "
  "FROM \"Person\" "
  "WHERE \"Person\".\"id\"=$1";

  const char access::object_traits_impl< ::kpk::data::Person, id_pgsql >::update_statement[] =
  "UPDATE \"Person\" "
  "SET "
  "\"name_first\"=$1, "
  "\"name_middle\"=$2, "
  "\"name_last\"=$3, "
  "\"name_full\"=$4, "
  "\"pass_series\"=$5, "
  "\"pass_number\"=$6, "
  "\"pass_date\"=$7, "
  "\"pass_org\"=$8, "
  "\"pass_orgCode\"=$9, "
  "\"inn\"=$10, "
  "\"snils\"=$11, "
  "\"idMember\"=$12 "
  "WHERE \"id\"=$13";

  const char access::object_traits_impl< ::kpk::data::Person, id_pgsql >::erase_statement[] =
  "DELETE FROM \"Person\" "
  "WHERE \"id\"=$1";

  const char access::object_traits_impl< ::kpk::data::Person, id_pgsql >::query_statement[] =
  "SELECT\n"
  "\"Person\".\"id\",\n"
  "\"Person\".\"name_first\",\n"
  "\"Person\".\"name_middle\",\n"
  "\"Person\".\"name_last\",\n"
  "\"Person\".\"name_full\",\n"
  "\"Person\".\"pass_series\",\n"
  "\"Person\".\"pass_number\",\n"
  "\"Person\".\"pass_date\",\n"
  "\"Person\".\"pass_org\",\n"
  "\"Person\".\"pass_orgCode\",\n"
  "\"Person\".\"inn\",\n"
  "\"Person\".\"snils\",\n"
  "\"Person\".\"idMember\"\n"
  "FROM \"Person\"\n"
  "LEFT JOIN \"Member\" AS \"idMember\" ON \"idMember\".\"id\"=\"Person\".\"idMember\"";

  const char access::object_traits_impl< ::kpk::data::Person, id_pgsql >::erase_query_statement[] =
  "DELETE FROM \"Person\"";

  const char access::object_traits_impl< ::kpk::data::Person, id_pgsql >::table_name[] =
  "\"Person\"";

  void access::object_traits_impl< ::kpk::data::Person, id_pgsql >::
  persist (database& db, object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj._id = id (sts.id_image ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::kpk::data::Person, id_pgsql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;
    using pgsql::update_statement;

    callback (db, obj, callback_event::pre_update);

    pgsql::transaction& tr (pgsql::transaction::current ());
    pgsql::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj._id);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::kpk::data::Person, id_pgsql >::
  erase (database& db, const id_type& id)
  {
    using namespace pgsql;

    ODB_POTENTIALLY_UNUSED (db);

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::kpk::data::Person, id_pgsql >::pointer_type
  access::object_traits_impl< ::kpk::data::Person, id_pgsql >::
  find (database& db, const id_type& id)
  {
    using namespace pgsql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::kpk::data::Person, id_pgsql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::kpk::data::Person, id_pgsql >::
  reload (database& db, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj._id);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::kpk::data::Person, id_pgsql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace pgsql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::kpk::data::Person, id_pgsql >::object_type >
  access::object_traits_impl< ::kpk::data::Person, id_pgsql >::
  query (database&, const query_base_type& q)
  {
    using namespace pgsql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += "\n";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        sts.connection (),
        query_statement_name,
        text,
        true,
        true,
        q.parameter_types (),
        q.parameter_count (),
        q.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) pgsql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::kpk::data::Person, id_pgsql >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      erase_query_statement_name,
      text,
      q.parameter_types (),
      q.parameter_count (),
      q.parameters_binding ());

    return st.execute ();
  }
}

#include <odb/post.hxx>
